### ISSUE TITLE
CSS, Fonts

### ISSUE THREAD

**Issue by mix1** [mix1/lotoshop#50]
CSS on veits kaos, includesin praegu erinevaid faile et nav oleks enamvähem. Vaja ühtlustada ning lisaks font korda sättida igal pool

**Comment by triinuliis7** [comment]
värvida pilt ära (#F9F1E6)
widgetitele teine värv
loosidele teine värv
võta bold ära widgetitel
open sans igale poole
nupud korda
kastid
